<a href="https://colab.research.google.com/github/muchammadwr/churn-at-fit.ly/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analyst Professional Practical Exam Submission

**You can use any tool that you want to do your analysis and create visualizations. Use this template to write up your summary for submission.**

You can use any markdown formatting you wish. If you are not familiar with Markdown, read the [Markdown Guide](https://s3.amazonaws.com/talent-assets.datacamp.com/Markdown+Guide.pdf) before you start.

## 📝 Task List

Your written report should include written text summaries and graphics of the following:
- Data validation:   
  - Describe validation and cleaning steps for every column in the data
- Exploratory Analysis:  
  - Include two different graphics showing single variables only to demonstrate the characteristics of data  
  - Include at least one graphic showing two or more variables to represent the relationship between features
  - Describe your findings
- Definition of a metric for the business to monitor  
  - How should the business use the metric to monitor the business problem
  - Can you estimate initial value(s) for the metric based on the current data
- Final summary including recommendations that the business should undertake

*Start writing report here..*

## Business Understanding

### Background

Over the past two quarters, we’ve noticed churn creeping up in our subscriber base.
Retaining customers is absolutely critical for us right now — our cost of acquiring new users
is rising, and every customer who leaves puts more pressure on Marketing and Product.
Leadership has asked us to come back with a clear picture of what’s driving churn and
some practical actions we can take heading into the next quarter.
We’ve pulled together a dataset from a few different sources (user activity, customer
support, and account information). The files are messy — the data come from different
teams, use different conventions and don’t always align in how fields are structured or
captured. That’s life in the real world, but it’s also why this analysis is important.
Use these data as your starting point for a churn analysis, making sure you include
engagement, support activity, and plan type — those are things the business cares about.
Focus on identifying patterns, potential drivers of churn and any KPIs you think leadership
should be paying attention to. Interesting findings almost certainly sit across the different
sources as well as in any one of them, so I'm expecting you to bring them together before
you draw conclusions.
I would like you to perform the analysis and write a short report for me. I don’t need to see
any code, but I do want to read your thinking, how you handled any data cleaning and
interpretation, and how you got to your conclusions.

I've already asked the Product Manager and the Lead Engineer a few questions about the
data; you can see their answers here and here.
I also want you to prepare and deliver the presentation to senior leadership - you are ready
for the challenge! Remember they're not data specialists and will be focussed on what they
can do to address the problem of churn.
You can find more details about what I expect you to do here.
I will be on vacation for the next couple of weeks, but I know you can do this without my
support. If you need to make any decisions, include them in your work and I will review them
when I am back.

### Objectives

## Data Understanding

In [34]:
# Import Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Data Loading

In [35]:
account_info_df = pd.read_csv("https://raw.githubusercontent.com/muchammadwr/churn-at-fit.ly/refs/heads/main/data/da_fitly_account_info.csv")
customer_support_df = pd.read_csv("https://raw.githubusercontent.com/muchammadwr/churn-at-fit.ly/refs/heads/main/data/da_fitly_customer_support.csv")
user_activity_df = pd.read_csv("https://raw.githubusercontent.com/muchammadwr/churn-at-fit.ly/refs/heads/main/data/da_fitly_user_activity.csv")

### Data Validation

#### `account_info_df`

In [36]:
# Show 20 rows dataframe
account_info_df.sample(20)

,customer_id,email,state,plan,plan_list_price,churn_status
149,C10149,user10149@example.com,Louisiana,Free,0,NaN
381,C10381,user10381@example.org,New Hampshire,Free,0,NaN
59,C10059,user10059@example.com,Rhode Island,Basic,29,Y
60,C10060,user10060@example.org,Montana,Enterprise,95,NaN
319,C10319,user10319@example.net,Colorado,Basic,21,NaN
107,C10107,user10107@example.org,Florida,Basic,10,NaN
162,C10162,user10162@example.net,Maryland,Pro,32,Y
323,C10323,user10323@example.com,Wyoming,Basic,18,NaN
66,C10066,user10066@example.com,Vermont,Enterprise,140,NaN
297,C10297,user10297@example.net,Mississippi,Pro,48,NaN
294,C10294,user10294@example.net,Arizona,Pro,54,NaN
70,C10070,user10070@example.com,Iowa,Basic,17,NaN
304,C10304,user10304@example.com,New Hampshire,Pro,55,Y
329,C10329,user10329@example.com,Nebraska,Pro,32,Y
101,C10101,user10101@example.com,Arizona,Basic,26,NaN
90,C10090,user10090@example.com,Michigan,Free,0,NaN
250,C10250,user10250@example.org,Vermont,Enterprise,132,NaN
2,C10002,user10002@example.net,Oklahoma,Basic,24,NaN
127,C10127,user10127@example.com,Mississippi,Enterprise,120,NaN
286,C10286,user10286@example.org,Arizona,Pro,78,NaN

In [37]:
# Check dataframe information
account_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      400 non-null    object
 1   email            400 non-null    object
 2   state            400 non-null    object
 3   plan             400 non-null    object
 4   plan_list_price  400 non-null    int64
 5   churn_status     114 non-null    object
dtypes: int64(1), object(5)
memory usage: 18.9+ KB

In [38]:
# Check missing values
account_info_df.isna().sum()

customer_id          0
email                0
state                0
plan                 0
plan_list_price      0
churn_status       286
dtype: int64

In [39]:
# Check duplicate values
account_info_df.duplicated().sum()

np.int64(0)

#### `customer_support_df`

In [40]:
# Show 20 rows dataframe
customer_support_df.sample(20)

,ticket_time,user_id,channel,topic,resolution_time_hours,state,comments
784,2025-07-15 12:19:52.446435,10148,phone,other,28.06,0,NaN
841,2025-11-26 11:43:19.853951,10135,email,technical,4.10,0,NaN
647,2025-06-11 01:55:14.236649,10254,phone,billing,12.04,1,NaN
728,2025-07-04 16:30:47.598349,10284,email,account,11.59,1,NaN
21,2025-10-08 03:08:35.179265,10300,chat,other,11.37,1,NaN
190,2025-07-13 20:07:57.706474,10207,email,technical,10.61,1,NaN
706,2025-07-01 13:23:58.227355,10039,chat,technical,6.51,0,NaN
27,2025-07-19 07:20:02.031251,10374,phone,billing,18.06,1,NaN
52,2025-11-21 01:31:18.933091,10055,chat,technical,6.00,1,NaN
680,2025-07-12 12:32:51.019404,10079,email,technical,6.65,1,NaN
311,2025-08-15 21:24:40.492623,10134,chat,account,10.45,1,NaN
828,2025-08-14 11:30:40.204610,10042,chat,other,4.72,0,NaN
262,2025-07-13 15:37:17.574536,10237,email,billing,15.55,0,NaN
390,2025-08-30 00:55:58.266131,10242,phone,account,2.61,0,NaN
718,2025-11-18 11:00:34.386387,10026,phone,account,7.86,0,NaN
515,2025-08-12 22:50:07.432487,10391,chat,billing,6.06,0,NaN
319,2025-10-07 01:37:26.599347,10196,phone,account,11.62,1,NaN
369,2025-06-15 13:16:39.459490,10289,email,other,21.04,0,NaN
347,2025-10-25 20:30:36.641121,10065,phone,billing,16.48,0,NaN
187,2025-06-08 03:08:07.075727,10371,email,technical,8.46,1,NaN

In [41]:
customer_support_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_time            918 non-null    object
 1   user_id                918 non-null    int64
 2   channel                918 non-null    object
 3   topic                  918 non-null    object
 4   resolution_time_hours  918 non-null    float64
 5   state                  918 non-null    int64
 6   comments               46 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 50.3+ KB

In [42]:
customer_support_df.isna().sum()

ticket_time                0
user_id                    0
channel                    0
topic                      0
resolution_time_hours      0
state                      0
comments                 872
dtype: int64

In [43]:
customer_support_df.duplicated().sum()

np.int64(0)

#### `user_activity_df`

In [44]:
# Show 20 rows dataframe
user_activity_df.sample(20)

                     event_time  user_id     event_type
363  2025-09-13 15:38:24.239648    10048   read_article
315  2025-09-15 01:18:48.109488    10312  share_workout
64   2025-08-28 11:28:54.738366    10188   read_article
66   2025-10-09 17:05:47.800934    10120   read_article
226  2025-10-12 03:37:58.337253    10020   read_article
228  2025-11-04 05:02:39.285286    10363   read_article
194  2025-08-03 09:31:23.474648    10075    watch_video
135  2025-09-08 17:37:56.416575    10134  track_workout
121  2025-06-22 15:27:48.578978    10392   read_article
368  2025-10-17 14:10:32.655251    10197  share_workout
100  2025-11-27 21:46:37.363620    10367   read_article
337  2025-08-08 02:37:38.815964    10100  track_workout
265  2025-10-29 22:35:49.190327    10391  track_workout
257  2025-08-21 14:34:41.314712    10134   read_article
401  2025-08-03 06:00:38.346515    10210   read_article
128  2025-09-15 10:39:31.325343    10384  share_workout
33   2025-07-21 13:59:46.059434    10353  share_workout
441  2025-09-22 18:28:07.618295    10264    watch_video
274  2025-11-11 12:12:03.755044    10152    watch_video
328  2025-09-18 07:17:40.343381    10158   read_article

In [45]:
# check dataframe information
user_activity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445 entries, 0 to 444
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   event_time  445 non-null    object
 1   user_id     445 non-null    int64
 2   event_type  445 non-null    object
dtypes: int64(1), object(2)
memory usage: 10.6+ KB

In [46]:
# Check missing values
user_activity_df.isna().sum()

event_time    0
user_id       0
event_type    0
dtype: int64

In [47]:
# check duplicate values
user_activity_df.duplicated().sum()

np.int64(0)

## Data Preparation

## Exploratory Data Analysis (EDA)

## Visualization & Explanatory Analysis

## Conclusion & Recommendation

## ✅ When you have finished...
-  Publish your Workspace using the option on the left
-  Check the published version of your report:
	-  Can you see everything you want us to grade?
    -  Are all the graphics visible?
-  Review the grading rubric. Have you included everything that will be graded?
-  Head back to the [Certification Dashboard](https://app.datacamp.com/certification) to submit your practical exam report and record your presentation